on:
 push
jobs:
 pythonlambda:
  runs-on: ubuntu-latest
  steps:
  - uses: actions/checkout@v4
  - name: Configure AWS Credentials
    uses: aws-actions/configure-aws-credentials@v4
    with:
        aws-access-key-id: AKIAW3MD6H3C3NUKMLOD
        aws-secret-access-key: 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
        aws-region: us-east-1
  - run: aws s3 cp HelloWorld.zip s3://lambdafunction22/   
  - run: |
          aws lambda create-function \
          --function-name HelloWorld \
          --runtime python3.8 \
          --role arn:aws:iam::471112498885:role/lambdaexcustion \
          --handler HelloWorld.lambda_handler \
          --zip-file fileb://HelloWorld.zip
  - run: aws lambda invoke --function-name HelloWorld output.txt       
