on:
 push
jobs:
 pythonlambda:
  runs-on: ubuntu-latest
  steps:
  - uses: actions/checkout@v4
  - name: Configure AWS Credentials
    uses: aws-actions/configure-aws-credentials@v4
    with:
        aws-access-key-id: AKIAW3MD6H3C3NUKMLOD
        aws-secret-access-key: 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
        aws-region: us-east-1
  - run: aws s3 cp HelloWorld.zip s3://lambdafunction22/   
  - run: |
          aws cloudformation deploy --stack-name lambda-funtion --template-file template.yml --capabilities CAPABILITY_NAMED_IAM
  #- run: aws lambda invoke --function-name HelloWorld output.txt       
