on:
 push
jobs:
 pythonlambda:
  runs-on: ubuntu-latest
  steps:
  - uses: actions/checkout@v4
  - name: Configure AWS Credentials
    uses: aws-actions/configure-aws-credentials@v4
    with:
        aws-access-key-id: AKIAW3MD6H3C25CVRGQV
        aws-secret-access-key: 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
        aws-region: us-east-1
  - run: aws s3 cp HelloWorld.zip s3://lambdafunction22/      
